[versions]
kotlin = '1.4.32'
accompanist = "0.8.1"
compose = "1.0.0-beta05"
activity = '1.3.0-alpha07'
compose = '1.0.0-beta05'
core = '1.6.0-alpha02'
mavericks = '2.1.0-alpha01'
accompanist = '0.8.1'

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:7.0.0-alpha15"

accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

mavericks-compose = { module = "com.airbnb.android:mavericks-compose", version.ref = "mavericks" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }