[versions]
kotlin = '1.4.32'
ktor = '1.5.4'
kotlinx_coroutines = '1.4.3'
kotlinx_serialization = '1.2.0'
androidx_compose = '1.0.0-beta05'
androidx_activity = '1.3.0-alpha07'
androidx_core = '1.6.0-alpha02'
google_accompanist = '0.8.1'
airbnb_mavericks = '2.1.0-alpha01'
dropbox_store = '4.0.0'
pinterest_ktlint = '0.41.0'

[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:7.0.0-alpha15"

androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx_compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx_compose" }
androidx-compose-material-material = { module = "androidx.compose.material:material", version.ref = "androidx_compose" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_coroutines" }

kotlinx-serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }

jetbrains-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
jetbrains-ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
jetbrains-ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
jetbrains-ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
jetbrains-ktor-engine-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }

google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "google_accompanist" }
airbnb-mavericks-compose = { module = "com.airbnb.android:mavericks-compose", version.ref = "airbnb_mavericks" }
dropbox-store = { module = "com.dropbox.mobile.store:store4", version.ref = "dropbox_store" }
pinterest-ktlint = { module = "com.pinterest:ktlint", version.ref = "pinterest_ktlint" }